# Generated by Django 6.1 on 2026-09-08 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localidades',
            options={'managed': True, 'ordering': ['id_provincia', 'codigo'], 'verbose_name': 'Localidades', 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterField(
            model_name='localidades',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.provincias'),
        ),
    ]
