# Generated by Django 6.1.1 on 2026-09-15 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(blank=True, null=True, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de la Provincia')),
            ],
            options={
                'verbose_name': 'Provincias',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincias',
                'ordering': ['codigo'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(blank=True, null=True, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la Categoria')),
                ('id_provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globales.provincias')),
            ],
            options={
                'verbose_name': 'Localidades',
                'verbose_name_plural': 'Localidades',
                'db_table': 'localidades',
                'ordering': ['id_provincia', 'codigo'],
                'managed': True,
            },
        ),
    ]
