# Generated by Django 6.1.1 on 2026-09-15 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=4, null=True, verbose_name='Rubros')),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
                'db_table': 'rubro',
                'ordering': ['codigo'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subrubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=4, null=True, verbose_name='Rubros')),
                ('descripcion', models.TextField()),
                ('id_rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.rubro')),
            ],
            options={
                'verbose_name': 'Subrubro',
                'verbose_name_plural': 'Subrubros',
                'db_table': 'subrubro',
                'ordering': ['codigo'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Rubros')),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('stock_minimo', models.IntegerField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedores')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.rubro')),
                ('subrubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.subrubro')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['codigo'],
                'managed': True,
            },
        ),
    ]
