# Generated by Django 6.1 on 2026-09-07 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('global', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Empresa')),
                ('domicilio', models.CharField(max_length=100, verbose_name='Domicilio')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.localidades')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.provincias')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
                'ordering': ['codigo'],
                'managed': True,
            },
        ),
    ]
