# Generated by Django 6.1.1 on 2026-09-15 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Empresa')),
                ('domicilio', models.CharField(max_length=100, verbose_name='Domicilio')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globales.localidades')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globales.provincias')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['codigo'],
                'managed': True,
            },
        ),
    ]
